backend/requirements.txt

This is used as production server

Add gunicorn to requirements.txt

---

backend/ordd/settings.py.tmpl
backend/ordd_api/mailer.py
backend/ordd_api/templates/ordd_api/mail_templates/create_by_owner.html
backend/ordd_api/templates/ordd_api/mail_templates/create_by_reviewer.html
backend/ordd_api/templates/ordd_api/mail_templates/delete_by_owner.html
backend/ordd_api/templates/ordd_api/mail_templates/delete_by_reviewer.html
backend/ordd_api/templates/ordd_api/mail_templates/update_by_owner.html
backend/ordd_api/templates/ordd_api/mail_templates/update_by_owner.txt
backend/ordd_api/templates/ordd_api/mail_templates/update_by_reviewer.html
backend/ordd_api/templates/ordd_api/mail_templates/update_by_reviewer.txt
backend/ordd_api/views.py

Add mail to reviewer when owner create, update and delete a dataset.
Add mail to dataset owner when reviewer delete a dataset owned by he/she.
Some cleanup.

Be mail to reviewer

---

backend/contents/key_datasets/kd-perils.csv
backend/ordd_api/__init__.py
backend/ordd_api/management/commands/load_key_datasets.py
backend/verifier-guest.sh

Removed kd-peril.csv and set ``is_peril`` field of ``KeyPeril`` model during load phase properly.
Tests are green here: https://ci.openquake.org/job/zdevel_open-risk-data-dashboard/41/

Be set is peril

---

backend/ordd_api/__init__.py
backend/ordd_api/views.py

Add fullscores indexes in ``/scoring`` and ``/scoring/<nation_code>`` viewes.
Test are running here: https://ci.openquake.org/job/zdevel_open-risk-data-dashboard/42/

Be fullscore indexes

---

backend/ordd_api/views.py

This PR send notifications to the right users.
Fix https://github.com/GFDRR/open-risk-data-dashboard/issues/80 issue.

notifications to 'admin' and 'reviewer' users, properly

---

backend/ordd_api/__init__.py
backend/ordd_api/models.py

Creation of new Dataset instance was broken, fix #125.

many2many relationships need instance to be saved before use them.

---

backend/ordd_api/views.py

Calculate a proper rank for countries without datasets associated.

update ranking computation for countries without datasets

---

frontend/index.html

Wrap the main title in a container and give it a size of 12 columns

---

frontend/css/rodi_css.css
frontend/index.html
frontend/js/angular/controller.js

- Remove js
- remove loading gif
- Remove CSS font class
- Set default text for values index

Home page optim

---

frontend/css/rodi_css.css
frontend/index.html

- mobile layout fix
- magnify with flex system
- remove loading google webfont from css

balloon fix 

---

frontend/css/rodi_css.css
frontend/index.html
frontend/views/web_menu.html

- button toggle aligned with logo
- used font awesome icon instead of bootstrap hamburger
- change color and animation to button open/close
- mobile menu open inline view (first step)

mobile web menu

---

frontend/css/rodi_css.css

- fix web menu low resolution mobile

fixing web menu for low all resolution mobile

---

frontend/about.html
frontend/confirm_registration.html
frontend/contribute.html
frontend/countries.html
frontend/css/rodi_css.css
frontend/dataset_details.html
frontend/dataset_list.html
frontend/error_404.html
frontend/index.html
frontend/methodology.html
frontend/password_reset.html
frontend/privacy.html
frontend/register.html
frontend/stats.html

- container (not fluid) for all pages
- SVG convert main logo for all pages
- fix category menu - roll back problem with fix webmenu mobile

SVG main logo 

---

frontend/js/angular/app.js

I propose two changes:
- update the production API address instead of the decommissioned one
- by default use the production URL instead of the local API

Provide more sensible defaults to the app

---

frontend/about.html

Add ABOUT title and sub menu for the page.
Add for any section a "back to top" link.

Bug: About page missing

---

frontend/about.html
frontend/confirm_registration.html
frontend/contribute.html
frontend/countries.html
frontend/dataset_details.html
frontend/dataset_list.html
frontend/error_404.html
frontend/index.html
frontend/methodology.html
frontend/password_reset.html
frontend/privacy.html
frontend/register.html
frontend/stats.html

#210 fix increase .col-xs-7 ----> .col-xs-8 of logo section and decrease .col-xs-5 ----> .col-xs-4 for  hamburger button, for all pages

increase logo column on mobile version

---

frontend/views/web_menu.html

#213 fix
put ng-if in li element instead of children tag, so when logged out last element will be disabled

Last menu element take some null space

---

frontend/css/rodi_css.css
frontend/dataset_list.html

Screenshot doesn't show the cursor but it changes to be a pointer as a normal click

#227 Country page: make the entire row clickable to see its details

---

frontend/index.html

Align home hamburger btn with main logo

---

docs/interview-guide.md

Here is a proposal of question to learn more about the product value and about the user flow within the website.
It can be found in the `docs/interview-guide.md` file.
fix #189 
It relies on #177 being merged first.

Interview guide

---

frontend/README.md

Corrected a typo

---

frontend/css/rodi_css.css

Something like that:
With hover effect:

feat(227) proposition of better display of criteria in dataset list

---

frontend/js/angular/controller_mainmenu.js

Bug email format check

---

frontend/countries.html

Remove div containing info on number of datasets considered

Remove datasets considered (Issue #275)

---

docs/_config.yml
docs/glossary.md
docs/lean-metrics.md
docs/user-journeys.md

The `docs` folder is intended to grow content shared within the @GFDRR organisation, to share the UX research results, mockups and thinking materials from within a same place.

Minimalistic documentation folder

---

frontend/css/rodi_css.css
frontend/css/table_color.css

Use colorblind accessible colours for open data criteria

---

frontend/css/rodi_css.css
frontend/css/table_style_20180221.css
frontend/dataset_list.html

Mobile view: 
Tablet view: 
Desktop view: 
fixes #228

#228 Country page: visually align and balance the metrics

---

frontend/countries.html
frontend/css/table_style_20180221.css
frontend/js/angular/controller.js

Display open data value as a progressbar

---

frontend/countries.html
frontend/css/rodi_css.css
frontend/js/angular/controller.js

Explore countries: add countries and region filters

---

frontend/countries.html
frontend/css/rodi_css.css
frontend/dataset_list.html
frontend/js/angular/controller_dataset_list.js
frontend/views/web_menu.html

This still has to be tested on Edge 15.
fixes #272

Simplify navigation colours interactions to possibly remove a timing issue in Edge browser

---

frontend/dataset_list.html

Fixed #308 
I don't know why but code has changed since pull request #273 and there was an issue on Tooltip for Hazard icons on dataset_list.
Should be fixed now.

Fixed #308 

---

frontend/js/angular/app.js
infrastructure/nginx/sites-available/development

allow integration between arbitrary BE and FE (not yet merged in master branch)
deploy on the new folder ``http-exp`` is manual and made on purpose only.
@daniviga @CIMAManuel

add an experimental infrastructure

---

frontend/contribute.html
frontend/js/angular/controller_mainmenu.js
frontend/password_reset.html
frontend/register.html
frontend/views/login_form.html

This way, they can work with password managers and browser autocomplete mechanisms.
fixes #179

Transform login, registration and My Profile into proper HTML forms

---

frontend/contribute.html
frontend/dataset_details.html
frontend/js/angular/controller.js
frontend/js/angular/controller_dataset_details.js
frontend/js/angular/service.js

I did my best to locate all references to `selectedTags`, `datasetTags`, `sTagsInfo` and `sTagsMsg`.
fix #342

Remove code related to Dataset Elements

---

frontend/about.html
frontend/confirm_registration.html
frontend/contribute.html
frontend/countries.html
frontend/dataset_details.html
frontend/dataset_list.html
frontend/email_data64.html
frontend/email_link.html
frontend/error_404.html
frontend/getdata.html
frontend/index.html
frontend/methodology.html
frontend/news-details.html
frontend/package-lock.json
frontend/package.json
frontend/password_reset.html
frontend/privacy.html
frontend/register.html
frontend/stats.html
frontend/views/footer.html
package-lock.json

It verifies missing tags, code typo and enforces safe ways of writing HTML.
It would have avoided the enclosed tag of #346, for example.
To be merged, the HTML errors should be fixed.

Run htmlhint to very tag compliance

---

frontend/css/rodi_css.css
frontend/dataset_details.html

Also, match InnovationLab guidelines (white on red)
👁‍🗨 [Live preview](https://deploy-preview-351--index-opendri-preview.netlify.com/)
fix #234

Restore Back button and change its label

---

backend/ordd/settings.py.tmpl
infrastructure/nginx/sites-available/experimental

fix configurations for development and experimemtal instances and improved django configuration.

improved cors configuration for django-rest-framework and nginx

---

frontend/contribute.html
frontend/views/login_form.html

This regression was introduced by b208872733f0896790cf8e6d733ca50aa2fb55fe, in #180.

Fix login buttons

---

frontend/dataset_details.html

- Add TITLE filed in Dataset edit form
- Mandatory check is already done in issue #354 
- Insert label class to conform to submit graphic

FE issue #355: Add Title filed in dataset edit form

---

frontend/contribute.html
frontend/js/angular/service.js

- Add mandatory text field in submit view for Title
- Add check in service.js for empty filed
- Add title label in new Dataset Object definition

FE issue #354: Add Title field in dataset submit page

---

frontend/js/angular/service.js

Add "null" value in check condition
fix #364

FE issue #364: change check function in service.js file

---

frontend/dataset_details.html

Otherwise it displays `Untitled`.
fix #329

Display dataset title

---

frontend/css/rodi_css.css
frontend/dataset_details.html

It's an intermediary step before #341.
👁‍🗨 [**live preview**](https://deploy-preview-370--index-opendri-preview.netlify.com/)
refs #340

Dataset Details: rework metadata layout

---

frontend/css/rodi_css.css
frontend/dataset_details.html

Bigger dataset title
Bigger open data logo
Removed buttons at the top when reviewer
Fix #373

Removed buttons at the top when reviewer

---

backend/ordd_api/__init__.py
backend/ordd_api/views.py

for each key-dataset the score associated is related just to the first dataset others are set arbitrarily to 50.0 just to avoid to be skipped by frontend.

return all datasets related to each key dataset

---

frontend/css/rodi_css.css
frontend/dataset_details.html
frontend/js/angular/controller_dataset_details.js
frontend/js/angular/controller_dataset_list.js
frontend/js/angular/service.js

Move related datasets on the right hand side of the page

---

docs/interview/danny.md

Transcript of Danny interview

---

frontend/countries.html

Temporarily remove filters from Explore Countries page

---

frontend/js/angular/app.js

Add polyfill for Array.prototype.find()

---

frontend/about.html
frontend/confirm_registration.html
frontend/contribute.html
frontend/countries.html
frontend/dataset_details.html
frontend/dataset_list.html
frontend/email_data64.html
frontend/email_link.html
frontend/error_404.html
frontend/getdata.html
frontend/index.html
frontend/js/angular/app.js
frontend/js/angular/controller.js
frontend/js/angular/controller_confirm_mail.js
frontend/js/angular/controller_dataset_details.js
frontend/js/angular/controller_dataset_list.js
frontend/js/angular/controller_mainmenu.js
frontend/js/angular/controller_reset_password.js
frontend/js/angular/service.js
frontend/methodology.html
frontend/news-details.html
frontend/password_reset.html
frontend/privacy.html
frontend/register.html
frontend/stats.html
frontend/views/footer.html
frontend/views/login_form.html
frontend/views/web_menu.html

I did several things in this pull request:
- I removed Angular main behaviour, that intercepts links and rewrite them base on an HTML attribute
- I replaced links that looks like buttons by… buttons
- I removed all `ng-click` related to page navigation on links (I kept them for non-links elements)
👁 [**Live Preview**](https://5c5aa28d8336840008576d9c--index-opendri-preview.netlify.com/)

Rework page navigation (via changeview(), changepage(), buttons and links)

---

frontend/css/rodi_css.css
frontend/index.html
frontend/views/footer.html

Modify text on home page

---

frontend/contribute.html
frontend/methodology.html
frontend/views/web_menu.html

Fix  #436 except email content

Change register to sign up

---

frontend/countries.html
frontend/js/angular/controller.js

Sort countries on opennness indicators

---

frontend/js/angular/controller.js

The filters reset was never resetting the settings.
fix #440

Fix Countries filters reset

---

frontend/css/rodi_css.css
frontend/dataset_list.html

Enhancement of multiple datasets table

---

frontend/js/angular/app.js

When #447 is deployed on `dev.riskopendata.org`, merge this pull request.

Sync dev FE with dev BE v2.3.1

---

frontend/css/rodi_css.css
frontend/dataset_details.html

Display dataset links with more emphasis

---

frontend/confirm_registration.html
frontend/contribute.html
frontend/error_404.html
frontend/index.html
frontend/methodology.html
frontend/views/footer.html
frontend/views/web_menu.html

Submit a dataset -> Add a dataset

---

frontend/about.html

Replaced opendri [at] understandrisk [dot] org with opendri [at] gfdrr [dot] org.

Changed contact us email

---

frontend/dataset_list.html
frontend/js/angular/controller_dataset_list.js

👁 [**live preview**](https://deploy-preview-462--index-opendri-preview.netlify.com/)
fix #453
fix #395

Change country list filters and add sorting options

---

frontend/countries.html
frontend/css/table_style_20180221.css

4 indicators as stacked bars

---

frontend/countries.html
frontend/css/table_style_20180221.css
frontend/index.html

Minor changes for text in homepage

---

docs/interviews/README.md
docs/interviews/asha.md

Asha's interview
